/** Disposable protocol qualification, using the same executor and bare repository as sync.
 * This is not a publication coordinator and never retries a push. */
import * as Effect from "effect/Effect";
import * as Option from "effect/Option";
import * as Schema from "effect/Schema";
import type { PlatformError } from "effect/PlatformError";
import type { SchemaError } from "effect/Schema";
import type * as Terminal from "effect/Terminal";
import type * as Prompt from "effect/cli/Prompt";
import type { OverleafGitError } from "./OverleafGitExecutor.ts";
import { OverleafGitExecutor, type OverleafGitExecuteResult } from "./OverleafGitExecutor.ts";
import * as Repository from "./OverleafRepository.ts";

export interface ProbeObservation {
  readonly name: string;
  readonly status: "passed" | "observed" | "unknown" | "failed" | "unverified";
  readonly facts: Readonly<Record<string, string | boolean | number>>;
}
export interface ProbeCandidate {
  readonly commit: string;
  readonly tree: string;
}
type ProbeHookError =
  | PlatformError
  | SchemaError
  | Terminal.QuitError
  | Repository.OverleafRepositoryError
  | OverleafGitError
  | string;
export interface ProbeHooks {
  /** Human browser actions in Cloud; a separate Git writer in the local rehearsal. */
  readonly browser: (
    stage: "edit" | "revert",
    input: {
      readonly prefix: string;
      readonly repo: string;
      readonly branch: "main" | "master";
      readonly candidate: ProbeCandidate;
    },
  ) => Effect.Effect<void, ProbeHookError, Prompt.Environment>;
  readonly observe: (
    observation: ProbeObservation,
  ) => Effect.Effect<void, ProbeHookError, Prompt.Environment>;
  readonly reviewMetadata: (
    stage: "before-rename" | "after-rename",
    prefix: string,
  ) => Effect.Effect<void, ProbeHookError, Prompt.Environment>;
}

export function cloudProbeGitUrl(input: string): string | null {
  const parsed = Schema.decodeUnknownOption(Schema.URLFromString)(input.trim());
  if (Option.isNone(parsed)) return null;
  const url = parsed.value;
  if (
    url.protocol !== "https:" ||
    url.username ||
    url.password ||
    url.port ||
    url.search ||
    url.hash
  )
    return null;
  const match =
    url.hostname === "www.overleaf.com"
      ? /^\/project\/([0-9a-f]{24})\/?$/u.exec(url.pathname)
      : url.hostname === "git.overleaf.com"
        ? /^\/([0-9a-f]{24})\/?$/u.exec(url.pathname)
        : null;
  return match ? `https://git.overleaf.com/${match[1]}` : null;
}

/** The report contains no manuscript bytes, project URL, credentials or raw errors. */
export function redactProbePushOutput(value: string, token: Uint8Array): string {
  const secret = new TextDecoder().decode(token);
  let redacted = value;
  if (secret) {
    redacted = redacted
      .replaceAll(secret, "[token]")
      .replaceAll(encodeURIComponent(secret), "[token]");
  }
  return redacted
    .replace(/https:\/\/[^\s]+/gu, "[remote]")
    .replace(/[\u0000-\u0008\u000b-\u001f\u007f]/gu, "")
    .slice(0, 4096);
}

/** Acceptance evidence is positive only. Missing or rewritten history stays unknown. */
export const probeAcceptance = Effect.fnUntraced(function* (input: {
  readonly repository: Repository.OverleafRepository["Service"];
  readonly repo: string;
  readonly before: string;
  readonly head: ProbeCandidate;
  readonly candidate: ProbeCandidate;
}) {
  if (input.head.tree === input.candidate.tree) return "current-tree" as const;
  const history = yield* input.repository
    .treesSince({ repo: input.repo, after: input.before, head: input.head.commit, limit: 64 })
    .pipe(Effect.option);
  if (Option.isSome(history) && history.value.some((entry) => entry.tree === input.candidate.tree))
    return "bounded-history-tree" as const;
  const reachable = yield* input.repository
    .isAncestor({
      repo: input.repo,
      ancestor: input.candidate.commit,
      descendant: input.head.commit,
    })
    .pipe(Effect.orElseSucceed(() => false));
  return reachable ? ("commit-reachable" as const) : ("unknown" as const);
});

export const runProtocolProbe = Effect.fn("OverleafProtocolProbe.run")(function* (input: {
  readonly repository: Repository.OverleafRepository["Service"];
  readonly git: OverleafGitExecutor["Service"];
  readonly repo: string;
  readonly witnessRepo: string;
  readonly gitUrl: string;
  readonly token: Uint8Array;
  /** Fresh safe namespace, generated by the host. */
  readonly prefix: string;
  readonly hooks: ProbeHooks;
}) {
  const { repository: repository, git, hooks, token, repo, prefix } = input;
  if (!/^scient-probe-[0-9a-f-]{36}$/u.test(prefix))
    return yield* new Repository.OverleafRepositoryError({
      reason: "invalid-tree",
      detail: "Invalid host-generated probe namespace.",
    });
  yield* repository.initialize({ repo, gitUrl: input.gitUrl });
  const branch = yield* repository.discoverBranch({ repo, token });
  if (branch === null)
    return yield* new Repository.OverleafRepositoryError({
      reason: "unreadable-output",
      detail: "No single main/master branch was advertised.",
    });
  yield* hooks.observe({ name: "authentication-and-branch", status: "passed", facts: { branch } });
  const initial = yield* repository.fetch({ repo, branch, token });
  const initialEntries = yield* repository.readTree({ repo, tree: initial.tree });
  if (initialEntries.length > 32 || initialEntries.some((entry) => entry.path.startsWith(prefix))) {
    return yield* new Repository.OverleafRepositoryError({
      reason: "invalid-tree",
      detail:
        "Use a fresh disposable project with at most 32 files and no probe namespace collision.",
    });
  }
  const makeCandidate = Effect.fnUntraced(function* (
    base: ProbeCandidate,
    files: Record<string, string>,
    removed: string[] = [],
  ) {
    const entries = (yield* repository.readTree({ repo, tree: base.tree })).filter(
      (entry) => !removed.includes(entry.path) && !(entry.path in files),
    );
    for (const [path, content] of Object.entries(files))
      entries.push({
        path,
        oid: yield* repository.writeBlob({ repo, bytes: new TextEncoder().encode(content) }),
      });
    const tree = yield* repository.writeTree({ repo, entries });
    const commit = yield* repository.commit({
      repo,
      tree,
      parents: [base.commit],
      message: "Scient disposable Git protocol test",
    });
    return { commit, tree };
  });
  const verifyFresh = Effect.fnUntraced(function* () {
    yield* repository.initialize({ repo: input.witnessRepo, gitUrl: input.gitUrl });
    return yield* repository.fetch({ repo: input.witnessRepo, branch, token });
  });
  const publish = Effect.fnUntraced(function* (name: string, candidate: ProbeCandidate) {
    yield* hooks.observe({ name: `${name}-attempt`, status: "observed", facts: { ...candidate } });
    const outcome = yield* repository.push({ repo, branch, commit: candidate.commit, token });
    yield* hooks.observe({
      name,
      status: outcome._tag === "accepted" ? "passed" : "unknown",
      facts: { outcome: outcome._tag },
    });
    // Do not send another candidate after an uncertain acknowledgement.
    if (outcome._tag !== "accepted")
      return yield* new Repository.OverleafRepositoryError({
        reason: "git-failed",
        detail: "Publication was not confirmed. Probe stopped without retry.",
      });
    const fresh = yield* verifyFresh();
    yield* hooks.observe({
      name: `${name}-fresh-read`,
      status: fresh.tree === candidate.tree ? "passed" : "failed",
      facts: {
        commitPreserved: fresh.commit === candidate.commit,
        treePreserved: fresh.tree === candidate.tree,
        publishedCommit: candidate.commit,
        observedCommit: fresh.commit,
      },
    });
    if (fresh.tree !== candidate.tree)
      return yield* new Repository.OverleafRepositoryError({
        reason: "git-failed",
        detail: "Fresh read differs. Stop for investigation without replay.",
      });
    return yield* repository.fetch({ repo, branch, token });
  });
  const marker = (value: string) => `% Scient disposable probe\n${value}\n`;
  const first = yield* makeCandidate(initial, {
    [`${prefix}/review.tex`]: marker("PROBE_INITIAL"),
    [`${prefix}/folder/child.tex`]: marker("PROBE_FOLDER"),
  });
  let current = yield* publish("initial-push", first);
  yield* hooks.reviewMetadata("before-rename", prefix);
  yield* hooks.browser("edit", { prefix, repo, branch, candidate: current });
  const browserState = yield* repository.fetch({ repo, branch, token });
  // This candidate is intentionally based on the pre-browser head.
  const stale = yield* makeCandidate(current, {
    [`${prefix}/stale.tex`]: marker("DO_NOT_ACCEPT_STALE"),
  });
  const rejected = yield* repository.push({ repo, branch, commit: stale.commit, token });
  yield* hooks.observe({
    name: "stale-push",
    status: rejected._tag === "out-of-date" ? "passed" : "failed",
    facts: { outcome: rejected._tag },
  });
  if (rejected._tag !== "out-of-date")
    return yield* new Repository.OverleafRepositoryError({
      reason: "git-failed",
      detail: "Unexpected stale-push response. Stop; do not retry.",
    });
  const afterEdit = yield* verifyFresh();
  yield* hooks.observe({
    name: "stale-push-left-remote-unchanged",
    status: afterEdit.tree === browserState.tree ? "passed" : "failed",
    facts: {
      unchanged: afterEdit.tree === browserState.tree,
      staleTreePresent: afterEdit.tree === stale.tree,
    },
  });
  if (afterEdit.tree !== browserState.tree)
    return yield* new Repository.OverleafRepositoryError({
      reason: "git-failed",
      detail: "Remote changed after rejection. Stop for investigation.",
    });
  current = yield* repository.fetch({ repo, branch, token });
  const renamePaths = new Map([
    [`${prefix}/review.tex`, `${prefix}/renamed.tex`],
    [`${prefix}/folder/child.tex`, `${prefix}/renamed-folder/child.tex`],
  ]);
  const renamedTree = yield* repository.writeTree({
    repo,
    entries: (yield* repository.readTree({ repo, tree: current.tree })).map((entry) => ({
      ...entry,
      path: renamePaths.get(entry.path) ?? entry.path,
    })),
  });
  const renamed = {
    tree: renamedTree,
    commit: yield* repository.commit({
      repo,
      tree: renamedTree,
      parents: [current.commit],
      message: "Scient disposable file and folder rename test",
    }),
  };
  current = yield* publish("file-and-folder-rename", renamed);
  yield* hooks.reviewMetadata("after-rename", prefix);
  const uncertain = yield* makeCandidate(current, { [`${prefix}/ack.tex`]: marker("PROBE_ACK") });
  // Simulate a lost acknowledgement after a real non-force push. This does not
  // claim to inject a TCP fault or prove when the Cloud server processes one.
  let actualResponse: OverleafGitExecuteResult | undefined;
  const dropping = OverleafGitExecutor.of({
    availability: git.availability,
    execute: Effect.fnUntraced(function* (command) {
      const result = yield* git.execute(command);
      if (command.args[0] === "push") {
        actualResponse = result;
        return { ...result, stdout: new Uint8Array(), stderr: "simulated lost acknowledgement" };
      }
      return result;
    }),
  });
  const uncertainPublisher = yield* Repository.make.pipe(
    Effect.provideService(OverleafGitExecutor, dropping),
  );
  yield* hooks.observe({ name: "lost-ack-attempt", status: "observed", facts: { ...uncertain } });
  const unknown = yield* uncertainPublisher.push({ repo, branch, commit: uncertain.commit, token });
  yield* hooks.observe({
    name: "simulated-lost-ack",
    status: unknown._tag === "unknown" ? "passed" : "failed",
    facts: {
      outcome: unknown._tag,
      simulation: true,
      actualPushResponse: actualResponse
        ? Repository.parsePushPorcelain(
            new TextDecoder().decode(actualResponse.stdout),
            actualResponse.stderr,
          )._tag
        : "unavailable",
    },
  });
  if (
    unknown._tag !== "unknown" ||
    !actualResponse ||
    Repository.parsePushPorcelain(
      new TextDecoder().decode(actualResponse.stdout),
      actualResponse.stderr,
    )._tag !== "accepted"
  ) {
    return yield* new Repository.OverleafRepositoryError({
      reason: "git-failed",
      detail: "Simulated lost acknowledgement did not follow a confirmed push. Do not retry.",
    });
  }
  yield* hooks.browser("revert", { prefix, repo, branch, candidate: uncertain });
  const verified = yield* repository.fetch({ repo, branch, token });
  const acceptance = yield* probeAcceptance({
    repository,
    repo,
    before: current.commit,
    head: verified,
    candidate: uncertain,
  });
  yield* hooks.observe({
    name: "acceptance-after-browser-revert",
    status: acceptance === "unknown" ? "unknown" : "passed",
    facts: { evidence: acceptance, remoteTreeEqualsCandidate: verified.tree === uncertain.tree },
  });
  const independent = yield* verifyFresh();
  yield* hooks.observe({
    name: "final-independent-read",
    status: independent.tree === verified.tree ? "passed" : "failed",
    facts: { sameTree: independent.tree === verified.tree },
  });
  if (independent.tree !== verified.tree)
    return yield* new Repository.OverleafRepositoryError({
      reason: "git-failed",
      detail: "Independent final read differs. Stop for investigation without replay.",
    });
  yield* hooks.observe({
    name: "real-network-loss",
    status: "unverified",
    facts: { simulatedAcknowledgementOnly: true },
  });
  return { branch, prefix };
});
