// Generated by compare-real-applier.mjs from the independent revision-5 checker.
// Checker engine SHA256 d7bc2275ef2647fd93513ab85e5864406540c24a87b4e5556ef44e28f46d501d; git version 2.39.0. No production base functions imported.
export const modelCases = [
  {
    native: false,
    crash: false,
    action: "none",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: false,
    crash: false,
    action: "source-edit",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: false,
    crash: true,
    action: "none",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: false,
    crash: true,
    action: "source-edit",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: true,
    crash: false,
    action: "none",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: true,
    crash: false,
    action: "source-edit",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: true,
    crash: true,
    action: "none",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
  {
    native: true,
    crash: true,
    action: "source-edit",
    base: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    captured: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    target: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    remote: {
      "new.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    expectedBase: {
      "old.tex":
        "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L1\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
    },
    later:
      "\\section{paper}\npaper context one\npaper context two\npaper context three\nr1: L2\npaper context four\npaper context five\npaper context six\nr2: R1\npaper context seven\npaper context eight\npaper context nine\n",
  },
] as const;
