import * as Effect from "effect/Effect";
import * as Schema from "effect/Schema";
import { TrimmedNonEmptyString } from "./baseSchemas.ts";
import { ProviderInstanceId } from "./providerInstance.ts";
import { ModelReasoningMetadata } from "./modelReasoning.ts";

export const CustomModelReasoningOverride = Schema.Struct({
  supported: Schema.Boolean,
  levels: Schema.Array(
    Schema.Literals(["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
  ),
  defaultLevel: Schema.optionalKey(
    Schema.Literals(["off", "minimal", "low", "medium", "high", "xhigh", "max"]),
  ),
});

const Label = TrimmedNonEmptyString.check(Schema.isMaxLength(256));
export const CustomModelId = Schema.String.check(Schema.isPattern(/^[a-zA-Z0-9_-]{1,80}$/));
export const CustomModelProtocol = Schema.Literals([
  "openai-completions",
  "openai-responses",
  "anthropic-messages",
]);
export type CustomModelProtocol = typeof CustomModelProtocol.Type;

/** Connection eligibility, not runtime installation or account readiness. */
export function supportsModelConnections(
  driver: string | undefined,
  protocol?: CustomModelProtocol,
): boolean {
  return (
    (driver === "pi" || driver === "droid") &&
    (protocol === undefined || CustomModelProtocol.literals.includes(protocol))
  );
}
export const CustomModel = Schema.Struct({
  id: CustomModelId,
  modelId: Label,
  name: Label,
  /** Absent on existing saved models, whose explicit settings remain authoritative. */
  configurationMode: Schema.optionalKey(Schema.Literals(["automatic", "manual"])),
  contextWindow: Schema.optionalKey(
    Schema.Int.check(Schema.isBetween({ minimum: 1024, maximum: 10_000_000 })),
  ),
  maxOutputTokens: Schema.optionalKey(
    Schema.Int.check(Schema.isBetween({ minimum: 1, maximum: 1_000_000 })),
  ),
  images: Schema.Boolean,
  /** Independent of limits. Absent preserves the legacy configuration's image intent. */
  imageInput: Schema.optionalKey(Schema.Literals(["automatic", "enabled", "disabled"])),
  reasoning: Schema.Boolean,
  /** Scient's preferred default; independent of provider capability evidence. */
  defaultReasoningLevel: Schema.optionalKey(
    Schema.Literals(["minimal", "low", "medium", "high", "xhigh", "max"]),
  ),
  /** Explicit user assertion, never presented as provider-verified metadata. */
  reasoningOverride: Schema.optionalKey(CustomModelReasoningOverride),
  /** Server-resolved during explicit setup and persisted; client-submitted claims are ignored. */
  reasoningMetadata: Schema.optionalKey(ModelReasoningMetadata),
  instanceIds: Schema.Array(ProviderInstanceId).check(Schema.isMaxLength(100)),
});
export type CustomModel = typeof CustomModel.Type;

export function customModelImageInput(model: CustomModel): "automatic" | "enabled" | "disabled" {
  return (
    model.imageInput ??
    (model.configurationMode === "automatic" ? "automatic" : model.images ? "enabled" : "disabled")
  );
}
export const CustomModelConnection = Schema.Struct({
  id: CustomModelId,
  name: Label,
  protocol: CustomModelProtocol,
  baseUrl: TrimmedNonEmptyString.check(Schema.isMaxLength(2048)),
  models: Schema.Array(CustomModel).check(Schema.isMaxLength(200)),
  /** Opaque server-generated reference, never a credential value. */
  credentialId: Schema.NullOr(CustomModelId),
  /** Display-only hint generated by the server; never a complete key. */
  apiKeySuffix: Schema.optionalKey(Schema.NullOr(Schema.String.check(Schema.isMaxLength(4)))),
});
export type CustomModelConnection = typeof CustomModelConnection.Type;

/** Non-secret configuration identity used to reject an outdated discovery assessment. */
export function customModelAttachmentKey(
  connection: CustomModelConnection,
  model: CustomModel,
): string {
  return JSON.stringify([
    connection.baseUrl,
    connection.protocol,
    connection.credentialId,
    model.modelId,
    model.configurationMode,
    model.contextWindow,
    model.maxOutputTokens,
    model.images,
    model.imageInput,
    model.reasoning,
    model.reasoningOverride,
    // Evidence timestamps and labels do not invalidate an identical runtime configuration.
    model.reasoningMetadata && [
      model.reasoningMetadata.status,
      model.reasoningMetadata.supported,
      model.reasoningMetadata.levels,
      model.reasoningMetadata.defaultLevel,
      model.reasoningMetadata.mode,
      model.reasoningMetadata.contextWindow,
      model.reasoningMetadata.maxOutputTokens,
      model.reasoningMetadata.images,
    ],
  ]);
}

export const ModelConnectionReadiness = Schema.Struct({
  connectionId: CustomModelId,
  modelId: CustomModelId,
  configurationKey: Schema.String,
  state: Schema.Literals(["available", "needs_setup"]),
  reason: Schema.optionalKey(Schema.Literals(["credential", "model_unavailable"])),
  contextWindow: Schema.optionalKey(Schema.Number),
  maxOutputTokens: Schema.optionalKey(Schema.Number),
  source: Schema.optionalKey(Schema.Literals(["agent", "manual", "provider", "catalog"])),
});
export type ModelConnectionReadiness = typeof ModelConnectionReadiness.Type;
export const CustomModelsSettings = Schema.Struct({
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)).pipe(
    Schema.withDecodingDefault(Effect.succeed(0)),
  ),
  connections: Schema.Array(CustomModelConnection)
    .check(Schema.isMaxLength(100))
    .pipe(Schema.withDecodingDefault(Effect.succeed([]))),
});
export type CustomModelsSettings = typeof CustomModelsSettings.Type;
export const CustomModelSaveInput = Schema.Struct({
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  connection: Schema.Struct({
    id: CustomModelId,
    name: Label,
    protocol: CustomModelProtocol,
    baseUrl: TrimmedNonEmptyString.check(Schema.isMaxLength(2048)),
    models: Schema.Array(CustomModel).check(Schema.isMaxLength(200)),
  }),
  apiKey: Schema.optionalKey(Schema.Redacted(Schema.String)),
  removeKey: Schema.optionalKey(Schema.Boolean),
  /** Explicit setup action; never refresh metadata on ordinary settings reads or turns. */
  refreshModelId: Schema.optionalKey(CustomModelId),
});
export type CustomModelSaveInput = typeof CustomModelSaveInput.Type;
export const CustomModelRemoveInput = Schema.Struct({
  revision: Schema.Int,
  connectionId: CustomModelId,
});
export const CustomModelTestInput = Schema.Struct({
  connectionId: CustomModelId,
  modelId: CustomModelId,
  instanceId: ProviderInstanceId,
  revision: Schema.Int,
});
export class CustomModelError extends Schema.TaggedError<CustomModelError>()("CustomModelError", {
  message: Schema.String,
}) {}

export function validateCustomModelConnection(
  connection: Omit<CustomModelConnection, "credentialId">,
): string | undefined {
  let url: URL;
  try {
    url = new URL(connection.baseUrl);
  } catch {
    return "Enter a valid endpoint URL.";
  }
  if (
    !["http:", "https:"].includes(url.protocol) ||
    url.username ||
    url.password ||
    url.search ||
    url.hash
  )
    return "Use an HTTP or HTTPS endpoint without credentials, query parameters, or a fragment.";
  if (
    connection.models.some(
      (model) =>
        model.configurationMode !== "automatic" &&
        (model.contextWindow === undefined ||
          model.maxOutputTokens === undefined ||
          !Number.isInteger(model.contextWindow) ||
          !Number.isInteger(model.maxOutputTokens) ||
          model.contextWindow < 1024 ||
          model.contextWindow > 10_000_000 ||
          model.maxOutputTokens < 1 ||
          model.maxOutputTokens > 1_000_000),
    )
  )
    return "Enter valid context and output limits.";
  if (
    connection.models.some(
      (model) =>
        model.configurationMode !== "automatic" && model.maxOutputTokens! > model.contextWindow!,
    )
  )
    return "Output limit cannot exceed the context window.";
  for (const model of connection.models) {
    const override = model.reasoningOverride;
    if (!override) continue;
    if (
      new Set(override.levels).size !== override.levels.length ||
      (!override.supported &&
        (override.levels.length > 0 || override.defaultLevel !== undefined)) ||
      (override.supported && override.levels.length === 0) ||
      (override.defaultLevel !== undefined && !override.levels.includes(override.defaultLevel))
    )
      return "Choose supported reasoning levels and a default from that list.";
  }
  if (
    new Set(connection.models.map((model) => model.id)).size !== connection.models.length ||
    new Set(connection.models.map((model) => model.modelId)).size !== connection.models.length
  )
    return "Each model must have a unique ID within its connection.";
  return undefined;
}
