export const MATH_TYPING_SHORTCUTS = {
  alpha: "\\alpha",
  beta: "\\beta",
  gamma: "\\gamma",
  delta: "\\delta",
  theta: "\\theta",
  lambda: "\\lambda",
  mu: "\\mu",
  pi: "\\pi",
  sigma: "\\sigma",
  phi: "\\phi",
  omega: "\\omega",
  inf: "\\infty",
  sqrt: "\\sqrt{#0}",
  sum: "\\sum_{#0}^{#1}",
  prod: "\\prod_{#0}^{#1}",
  int: "\\int_{#0}^{#1}",
  lim: "\\lim_{#0 \\to #1}",
  "->": "\\to",
  "<=": "\\le",
  ">=": "\\ge",
  "!=": "\\ne",
} as const;
